[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "MonoDetour"
name = "MonoDetour_BepInEx_5_Resonite"
description = "Full MonoDetour package (MonoDetour + MonoDetour.BepInEx.5) as a Resonite renderer preloader plugin. MonoDetour is an easy and convenient .NET detouring library, powered by MonoMod.RuntimeDetour."
websiteUrl = "https://github.com/MonoDetour/MonoDetour"
containsNsfwContent = false
[package.dependencies]
ResoniteModding-BepInExRenderer = "5.4.233001"
ResoniteModding-RenderiteHook = "1.1.1"

[build]
icon = "../../icon.png"
readme = "./README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour.BepInEx.5/release/0.com.github.MonoDetour.BepInEx.5.dll"
target = "Renderer/BepInEx/patchers/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour/release/netstandard2.0/com.github.MonoDetour.dll"
target = "Renderer/BepInEx/core/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour/release/netstandard2.0/com.github.MonoDetour.Reflection.dll"
target = "Renderer/BepInEx/core/"

[[build.copy]]
source = "../../artifacts/bin/MonoDetour/release/netstandard2.0/com.github.MonoDetour.Bindings.Reorg.dll"
target = "Renderer/BepInEx/core/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
# https://thunderstore.io/api/experimental/community/
communities = [
    "resonite",
]

[publish.categories]
# https://thunderstore.io/api/experimental/community/resonite/category/
resonite = [ "libraries", ]
