
[publish]
# https://thunderstore.io/api/experimental/community/
communities = [ "lethal-company", "repo", "riskofrain2", "peak" ]

[publish.categories]
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "libraries", ]
repo = [ "libraries", ]
riskofrain2 = [ "libraries", ]
peak = [ "libraries", ]
